"""Create messages table

Revision ID: f11aef2966f6
Revises: 5d5cc5324364
Create Date: 2024-10-21 08:48:30.417884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11aef2966f6'
down_revision = '5d5cc5324364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
